---
# role: repos
# file: tasks/apt.yml

- name: REPOS | Converge desired APT sources
  become: true
  become_user: root
  jomrr.general.repo_apt:
    path: "{{ __repos_repository.path }}"
    state: "{{ __repos_repository.state }}"
    default_enabled: "{{ repos_enabled }}"
    enabled: "{{ __repos_repository.enabled | default(omit) }}"
    types: "{{ __repos_repository.types | default(omit) }}"
    uris: "{{ __repos_repository.uris | default(omit) }}"
    suites: "{{ __repos_repository.suites | default(omit) }}"
    components: "{{ __repos_repository.components | default(omit) }}"
    architectures: "{{ __repos_repository.architectures | default(omit) }}"
    signed_by: "{{ __repos_repository.signed_by | default(omit) }}"
  loop: "{{ __repos_repositories }}"
  loop_control:
    loop_var: __repos_repository
    label: "{{ __repos_repository.path }}"
