---
# role: repos
# file: tasks/main.yml

- name: REPOS | Load distribution presets
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', __repos_platform_files) }}"
  vars:
    __repos_platform_files:
      files:
        - "{{ ansible_facts.distribution }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: REPOS | Validate requested repositories
  ansible.builtin.import_tasks: assert.yml

- name: REPOS | Converge repositories with the detected package manager
  ansible.builtin.include_tasks: "{{ __repos_backends[ansible_facts.pkg_mgr] }}.yml"
