---
# role: repos
# file: tasks/zypper.yml

- name: REPOS | Converge selected Zypper repositories
  become: true
  become_user: root
  jomrr.general.repo_rpm:
    backend: zypper
    path: "{{ __repos_repository.path }}"
    name: "{{ __repos_repository.name }}"
    state: "{{ __repos_repository.state }}"
    default_enabled: "{{ repos_enabled }}"
    default_gpgcheck: "{{ repos_gpgcheck }}"
    enabled: "{{ __repos_repository.enabled | default(omit) }}"
    description: "{{ __repos_repository.description | default(omit) }}"
    repo: "{{ __repos_repository.repo | default(omit) }}"
    gpgcheck: "{{ __repos_repository.gpgcheck | default(omit) }}"
    autorefresh: "{{ __repos_repository.autorefresh | default(omit) }}"
    auto_import_keys: "{{ __repos_repository.auto_import_keys | default(omit) }}"
    priority: "{{ __repos_repository.priority | default(omit) }}"
  loop: "{{ __repos_repositories }}"
  loop_control:
    loop_var: __repos_repository
    label: "{{ __repos_repository.name }}"
