---
# role: repos
# file: molecule/dev/molecule.yml

dependency:
  name: "galaxy"
  options:
    role-file: "${MOLECULE_PROJECT_DIRECTORY}/collections.yml"
    requirements-file: "${MOLECULE_PROJECT_DIRECTORY}/collections.yml"
driver:
  name: "podman"
provisioner:
  name: "ansible"
  config_options:
    defaults:
      forks: 8
      interpreter_python: "auto_silent"
      callbacks_enabled: "ansible.builtin.default"
      callback_result_format: "yaml"
      display_ok_hosts: false
      display_skipped_hosts: false
      show_task_path_on_failure: true
    connection:
      pipelining: true
  inventory:
    group_vars:
      all:
        ansible_podman_mount_detection: false
        __repos_test_directories:
          apt: "/etc/apt"
          dnf: "/etc/yum.repos.d"
          dnf5: "/etc/yum.repos.d"
          zypper: "/etc/zypp/repos.d"
        __repos_test_directory: "{{ __repos_test_directories[ansible_facts.pkg_mgr] }}"
        repos_apt: "{{ __repos_test_repositories[ansible_facts.distribution] if ansible_facts.pkg_mgr == 'apt' else [] }}"
        repos_dnf: "{{ __repos_test_repositories[ansible_facts.distribution] if ansible_facts.pkg_mgr in ['dnf', 'dnf5'] else\
          \ [] }}"
        repos_zypper: "{{ __repos_test_repositories[ansible_facts.distribution] if ansible_facts.pkg_mgr == 'zypper' else\
          \ [] }}"
        __repos_test_enabled: true
        __repos_test_mirror_version: "v1"
        __repos_test_repositories:
          AlmaLinux:
            - name: "molecule-repository"
              baseurl:
                - "file:///tmp/repos-fixture-{{ __repos_test_mirror_version }}"
              enabled: false
            - preset: "epel"
              enabled: "{{ __repos_test_enabled }}"
              baseurl:
                - "file:///tmp/repos-fixture-v1"
            - name: "crb"
              file: "almalinux-crb"
              enabled: false
              baseurl:
                - "file:///tmp/repos-fixture-v1"
            - name: "molecule-supplied"
              file: "molecule-settings"
              enabled: "{{ __repos_test_enabled }}"
              baseurl:
                - "file:///tmp/repos-fixture-mirror-{{ __repos_test_mirror_version }}"
          Debian:
            - name: "molecule-repository"
              uris:
                - "file:///tmp/repos-fixture-{{ __repos_test_mirror_version }}"
              suites:
                - "./"
              enabled: false
            - preset: "backports"
              enabled: "{{ __repos_test_enabled }}"
              uris:
                - "https://deb.debian.org/debian/"
            - path: "/etc/apt/sources.list.d/molecule-supplied.sources"
              suites:
                - "fixture-backports"
              uris:
                - "https://mirror.example.org/{{ __repos_test_mirror_version }}"
          Ubuntu:
            - name: "molecule-repository"
              uris:
                - "file:///tmp/repos-fixture-{{ __repos_test_mirror_version }}"
              suites:
                - "./"
              enabled: false
            - preset: "backports"
              enabled: "{{ __repos_test_enabled }}"
              uris:
                - "https://archive.ubuntu.com/ubuntu/"
            - path: "/etc/apt/sources.list.d/molecule-supplied.sources"
              suites:
                - "fixture-backports"
              uris:
                - "https://mirror.example.org/{{ __repos_test_mirror_version }}"
          Fedora:
            - name: "molecule-repository"
              baseurl:
                - "file:///tmp/repos-fixture-{{ __repos_test_mirror_version }}"
              enabled: false
            - preset: "rpmfusion_free"
              enabled: "{{ __repos_test_enabled }}"
              repositories:
                - name: "rpmfusion-free"
                  baseurl:
                    - "file:///tmp/repos-fixture-v1"
                - name: "rpmfusion-free-updates"
                  baseurl:
                    - "file:///tmp/repos-fixture-v2"
            - preset: "rpmfusion_nonfree"
              enabled: "{{ __repos_test_enabled }}"
            - name: "updates-testing"
              file: "fedora-updates-testing"
              enabled: "{{ __repos_test_enabled }}"
              baseurl:
                - "file:///tmp/repos-fixture-v1"
            - name: "molecule-supplied"
              file: "molecule-settings"
              enabled: "{{ __repos_test_enabled }}"
              baseurl:
                - "file:///tmp/repos-fixture-mirror-{{ __repos_test_mirror_version }}"
            - name: "fedora"
              enabled: "{{ __repos_test_enabled }}"
          openSUSE Leap:
            - name: "molecule-repository"
              repo: "file:///tmp/repos-fixture-{{ __repos_test_mirror_version }}"
              enabled: false
            - preset: "obs_devel_tools"
              enabled: "{{ __repos_test_enabled }}"
              repo: "file:///tmp/repos-fixture-preset-v1"
              auto_import_keys: false
            - preset: "obs_filesystems"
              enabled: "{{ __repos_test_enabled }}"
            - name: "molecule-supplied"
              file: "molecule-settings"
              enabled: "{{ __repos_test_enabled }}"
              repo: "file:///tmp/repos-fixture-mirror-{{ __repos_test_mirror_version }}"
          openSUSE Tumbleweed:
            - name: "molecule-repository"
              repo: "file:///tmp/repos-fixture-{{ __repos_test_mirror_version }}"
              enabled: false
            - preset: "obs_devel_tools"
              enabled: "{{ __repos_test_enabled }}"
              repo: "file:///tmp/repos-fixture-preset-v1"
              auto_import_keys: false
            - preset: "obs_filesystems"
              enabled: "{{ __repos_test_enabled }}"
            - name: "molecule-supplied"
              file: "molecule-settings"
              enabled: "{{ __repos_test_enabled }}"
              repo: "file:///tmp/repos-fixture-mirror-{{ __repos_test_mirror_version }}"
  log: true
  playbooks:
    prepare: "../resources/playbooks/prepare.yml"
    converge: "../resources/playbooks/converge.yml"
    verify: "../resources/playbooks/verify.yml"
    side_effect: "../resources/playbooks/side_effect.yml"
verifier:
  name: "ansible"
scenario:
  test_sequence:
    - "dependency"
    - "destroy"
    - "syntax"
    - "create"
    - "prepare"
    - "check"
    - "converge"
    - "idempotence"
    - "check"
    - "verify"
    - "side_effect"
    - "destroy"
  name: "dev"
platforms:
  - name: "almalinux-latest-repos"
    image: "docker.io/jomrr/molecule-almalinux:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
  - name: "debian-latest-repos"
    image: "docker.io/jomrr/molecule-debian:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
  - name: "fedora-latest-repos"
    image: "docker.io/jomrr/molecule-fedora:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
  - name: "opensuse-leap-latest-repos"
    image: "docker.io/jomrr/molecule-opensuse-leap:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
  - name: "opensuse-tumbleweed-latest-repos"
    image: "docker.io/jomrr/molecule-opensuse-tumbleweed:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
  - name: "ubuntu-latest-repos"
    image: "docker.io/jomrr/molecule-ubuntu:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
